version: "1.0"
services:
    
    

  benchmarks:
    container_name: "Benchmarks-for-backend-w.-queue-system"
    build:
      dockerfile: ./benchmarks/Benchmarks/Benchmark.Dockerfile
      args:
        CLIENT_PORT: $PORT
        CLIENT_TARGET: webserver
#    depends_on:
#      - integration-test
# 
#  integration-test:
#    container_name: "Integration-tests"
#    build:
#      dockerfile: ./benchmarks/CodeRunnerClientTest/Test.Dockerfile
#      args:
#        CLIENT_PORT: $PORT
#        CLIENT_TARGET: webserver
#    depends_on:
#      - webserver
# 
#  webserver:
#    env_file: .env
#    build:
#      dockerfile: ./backend/Webserver/Dockerfile