version: "1.0"
services:
  
  integration-test:
    container_name: "Integration-tests-$ENV_FILE_VERSION"
    build:
      dockerfile: ./benchmarks/CodeRunnerClientTest/Test.Dockerfile
      args:
        CLIENT_PORT: $PORT
        CLIENT_TARGET: webserver
    depends_on:
      webserver:
        condition: service_healthy
        
  webserver:
    container_name: "WEBAPP____$ENV_FILE_VERSION"
    ports:
      - $PORT:$PORT
    build:
      dockerfile: ./backend/webserver/Dockerfile2
    healthcheck: # I need help defining this
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  


