version: "1.0"
services:

  webserver:
    container_name: "WEBAPP_$ENV_FILE_VERSION"
    ports:
      - $PORT:$PORT
    build:
      dockerfile: ./backend/webserver - rocket/Dockerfile
      args:
        MAX_THREADS: $MAX_THREADS
        CHANNEL_BUFFER_CAPACITY: $CHANNEL_BUFFER_CAPACITY
        DURATION_BETWEEN_SWEEPS: $DURATION_BETWEEN_SWEEPS
        REQUEST_LIFETIME: $REQUEST_LIFETIME
        PORT: $PORT
        IP: $IP
    ulimits:
        nproc: 65535
        nofile:
            soft: 26677
            hard: 46677
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
      
  benchmark:
    container_name: "Benchmark_$ENV_FILE_VERSION"
    build:
      dockerfile: ./benchmarks/Benchmarks/Benchmark.Dockerfile
      args:
        CLIENT_PORT: $PORT
        CLIENT_TARGET: webserver
    volumes:
      - benchmarks-artifacts:/src/bin/publish/BenchmarkDotNet.Artifacts #might not be necessary to use volume.
    
volumes:
  benchmarks-artifacts:
  