name: database endpoint test
on: 
  push: 
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  POSTGRES_PASSWORD: test
  POSTGRES_USER: admin
  POSTGRES_DB: db
  DATABASE_URL: "postgres://admin:test@postgres:5432"
    
jobs:
  # Label of the container job
  Database-SetUp:
    # Containers must run in Linux based operating s  ystems
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./frontend
    # Docker Hub image that `container-job` executes in
    container: node:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:

        env:
          #The issues stem from here! If test or admin references the global env vars it fails...
          POSTGRES_PASSWORD: test
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: latest

        
      - name: install dependencies
        run: npx ci
      - name: migrate DB
        run: |
          echo "$DATABASE_URL"
          yarn prisma db push