name: database endpoint test
on: 
  push: 
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    
jobs:
  # Label of the container job
  Database-SetUp:
    # Containers must run in Linux based operating s  ystems
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./frontend
    # Docker Hub image that `container-job` executes in
    container: node:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:

        env:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports: 
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready

    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: latest

        
      - name: install dependencies
        run: npx ci
      - name: migrate DB
        run: |
          echo "$DATABASE_URL"
          yarn prisma db push


            
        
